version : '3'

services:
    db:
        build:
            context : ../
            dockerfile : ./Docker/configdb/Dockerfile
        environment:
            - MARIADB_ROOT_PASSWORD=1234
        ports:
            - "3306:3306"

    web:
        build:
            context: ../
            dockerfile: ./Docker/configweb/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./:/app/
